module.exports.ROUTES = {
  index: "/",
  play: "/play/:id/:pageNum",
  login: "/login",
  logout: "/logout",
  register: "/register",
  account: "/account",
  error: "/error",
  results: "/results",
  detailedResults: "/detailed-results/:id",
  playSettings: "/play-settings",
  sendPlayData: "/send-play-data",
  updatePlayData: "/update-play-data",
  test: "/test",
};
