module.exports.ROUTES = {
  index: "/",
  play: "/play",
  login: "/login",
  logout: "/logout",
  register: "/register",
  account: "/account",
  changeProfile: "/account/change-profile",
  updateProfile: "/update-profile",
  error: "/error",
  results: "/results",
  playSettings: "/play-settings",
  sendPlayData: "/send-play-data",
  updatePlayData: "/update-play-data",
  test: "/test",
};
